### ISSUE TITLE
Add `conda` installation option for `flowtorch`

### ISSUE THREAD

**Issue by sugatoray** [facebookincubator/flowtorch#80]
Adding a `conda` installation option for `flowtorch` could be very helpful. I have added `flowtorch` to conda-forge channel. The :bulb: [**PR**][#pr-conda-forge-flowtorch] was just merged.

[#pr-conda-forge-flowtorch]: https://github.com/conda-forge/staged-recipes/pull/17175

```sh
conda install -c conda-forge flowtorch
```

:zap: I will push a PR to update the readme-installation section.

> https://github.com/conda-forge/staged-recipes/pull/17175

**Comment by sugatoray** [comment]
:rocket: A screenshot is all you need!

![image](https://user-images.githubusercontent.com/10201242/145595994-b912afa1-ce0c-443e-a797-98bc9d4aed60.png)

**Comment by stefanwebb** [comment]
@sugatoray fantastic work! I really appreciate your doing this - it will be super useful to be able to install from Conda as well :)

Just a few questions about how it works: do you have to update the Conda recipe with a PR for each FlowTorch release, or it is connected to PyPI (i.e. when PyPI updates will Conda update too)?

Are you able to install it from Conda yet? I get a `PackagesNotFoundError` with `conda install -c conda-forge flowtorch` although maybe the changes take a while to propagate to the package metadata file?

**Comment by sugatoray** [comment]
> @sugatoray fantastic work! I really appreciate your doing this - it will be super useful to be able to install from Conda as well :)

Glad I could help!

> Just a few questions about how it works: do you have to update the Conda recipe with a PR for each FlowTorch release, or it is connected to PyPI (i.e. when PyPI updates will Conda update too)?

Typically, you need the maintainer(s) of `conda-forge/flowtorch-feedstock` to make a minor modification to a yaml file and push to the feedstock. Currently, I am the sole maintainer of this feedstock.

> Are you able to install it from Conda yet? I get a `PackagesNotFoundError` with `conda install -c conda-forge flowtorch` although maybe the changes take a while to propagate to the package metadata file?

Yes, it typically takes some time to propagate. But I just installed it. So, it should work now.

**Comment by stefanwebb** [comment]
Fantastic, I'll add you to https://flowtorch.ai/dev/about#contributors when I update the website next! :) The `conda install` is working for me now as well
