### ISSUE TITLE
Feature request: inverse bijector

### ISSUE THREAD

**Issue by vmoens** [facebookincubator/flowtorch#90]
### Feature Description
It'd be good to have an inverse layer, i.e. `g = f^{-1}(x)`.
The implementation is pretty straightforward:

```python
class InverseBijector(Bijector):
    def __init__(self, bijector):
        self.bijector = bijector
   
    def _forward(self, ...):
        y, log_detJ = self.bijector._inverse(...)
        log_detJ = -log_detJ  # as det(J(f)) = 1/det(J(g))
        return y, log_detJ

    def _inverse(self, ...):
        x, log_detJ =  self.bijector._forward(...)
        log_detJ = -log_detJ
        return x, log_detJ
 
```

We could also add an `invert()` method to the `Bijector` class:
```python
class Bijector:
    ...
    def invert(self) -> InverseBijector:
        return InverseBijector(self)

```
### Usage
Implicit flows, for instance, are a type of model that alternates forward and inverse calls to an invertible resnet block.
The simplest implementation i could think of would be 
```python
flow = Compose([
   layer1,
   layer2.invert(),
   ....])
```

**Comment by stefanwebb** [comment]
We've added this feature with #91 so closing :)
